CONTIKI_PROJECT = main
all: $(CONTIKI_PROJECT)

# Enable NULLNET
MAKE_MAC ?= MAKE_MAC_CSMA
MAKE_NET = MAKE_NET_NULLNET

# PROJECT_SOURCEFILES += ARQ_protocols.c


CONTIKI = ../..
include $(CONTIKI)/Makefile.include
